name: Rebuild Discourse Dev
concurrency: fixed
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: run launcher rebuild command via ssh
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DISCOURSE_DEV_HOST }}
          username: ${{ secrets.DISCOURSE_DEV_USERNAME }}
          password: ${{ secrets.DISCOURSE_DEV_PASSWORD }}
          port: 22
          command_timeout: 200m
          script: |
            docker exec -w /var/www/discourse -i app rake plugin:update[plural-polis-discourse]
            docker exec -w /var/www/discourse -i app rake assets:precompile
            /var/discourse/launcher restart app
